bank:
  notificationService: ${NOTIFICATION_SERVICE}
  exchangeGenService: ${EXCHANGE_GEN_SERVICE}
  exchangeService: ${EXCHANGE_SERVICE}
  cashService: ${CASH_SERVICE}
  transferService: ${TRANSFER_SERVICE}
  accountsService: ${ACCOUNTS_SERVICE}
  blockerService: ${BLOCKER_SERVICE}

server:
  port: ${GATEWAY_PORT}

spring:
  application:
    name: ${GATEWAY_SERVICE}
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: ${CONSUL_HOST}         # Адрес Consul (по умолчанию localhost)
      port: ${CONSUL_PORT}               # Порт Consul (8500 по умолчанию)
      discovery:
        register-health-check: false
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        prefixes: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
        defaultContext: application  # Контекст по умолчанию

    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: notification-service
              uri: lb://${bank.notificationService}       # адрес сервиса B
              predicates:
                - Path=/notification/**                # перехватываем путь
              filters:
                - RewritePath=/notification/?(?<segment>.*), /$\{segment}

            - id: exchange-gen-service
              uri: lb://${bank.exchangeGenService}       # адрес сервиса B
              predicates:
                - Path=/exchange-gen/**                # перехватываем путь
              filters:
                - RewritePath=/exchange-gen/?(?<segment>.*), /$\{segment}

            - id: exchange-service
              uri: lb://${bank.exchangeService}       # адрес сервиса B
              predicates:
                - Path=/exchange/**                # перехватываем путь
              filters:
                - RewritePath=/exchange/?(?<segment>.*), /$\{segment}

            - id: cash-service
              uri: lb://${bank.cashService}       # адрес сервиса B
              predicates:
                - Path=/cash/**                # перехватываем путь
              filters:
                - RewritePath=/cash/?(?<segment>.*), /$\{segment}

            - id: transfer-service
              uri: lb://${bank.transferService}       # адрес сервиса B
              predicates:
                - Path=/transfer/**                # перехватываем путь
              filters:
                - RewritePath=/transfer/?(?<segment>.*), /$\{segment}

            - id: accounts-service
              uri: lb://${bank.accountsService}       # адрес сервиса B
              predicates:
                - Path=/accounts/**                # перехватываем путь
              filters:
                - RewritePath=/accounts/?(?<segment>.*), /$\{segment}

            - id: blocker-service
              uri: lb://${bank.blockerService}       # адрес сервиса B
              predicates:
                - Path=/blocker/**                # перехватываем путь
              filters:
                - RewritePath=/blocker/?(?<segment>.*), /$\{segment}