spring:
  application:
    name: ${UI_SERVICE}
  mvc:
    favicon:
      enabled: false
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: ${CONSUL_HOST}          # Адрес Consul (по умолчанию localhost)
      port: ${CONSUL_PORT}               # Порт Consul (8500 по умолчанию)
      discovery:
        register-health-check: false
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        prefix: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
        defaultContext: application  # Контекст по умолчанию


chassis:
  servicePort: ${UI_PORT}
  oauthClientId: ${UI_OAUTH_ID}
  oauthClientSecret: ${UI_OAUTH_SECRET}
  oauthIssuerUri: "http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/realms/${KEYCLOAK_REALM}"