spring:
  application:
    name: transfer-service
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: localhost          # Адрес Consul (по умолчанию localhost)
      port: 8500               # Порт Consul (8500 по умолчанию)
      discovery:
        register-health-check: false
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        prefix: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
        defaultContext: application  # Контекст по умолчанию

chassis:
  servicePort: 8096
  oauthClientId: bankapp-srv
  oauthClientSecret: bF9xLjmjfaWDCO3CyuoSZkVBIV8bODL3
  oauthIssuerUri: "http://localhost:8080/realms/bankapp"