spring:
  application:
    name: exchange-service

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:stats;MODE=PostgreSQL
    username: test
    password: test

  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: localhost          # Адрес Consul (по умолчанию localhost)
      port: 8500               # Порт Consul (8500 по умолчанию)
      discovery:
        register-health-check: false
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        prefix: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
        defaultContext: application  # Контекст по умолчанию

chassis:
  servicePort: 8093
  oauthClientId: bankapp-srv
  oauthClientSecret: bF9xLjmjfaWDCO3CyuoSZkVBIV8bODL3
  oauthIssuerUri: "http://localhost:8080/realms/bankapp"